version: "3"
services:
  app-http:
    image: ${APP_NAME}
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - ${APP_HTTP_SERVER_PORT}:${APP_HTTP_SERVER_PORT}
      - ${DEBUGGER_PORT}:${DEBUGGER_PORT}
    command: ["go", "run", "cmd/http/main.go"]
    environment:
      - DD_SERVICE=${APP_NAME}-http

  app-grpc:
    image: ${APP_NAME}
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - ${APP_GRPC_SERVER_PORT}:${APP_GRPC_SERVER_PORT}
      - ${DEBUGGER_PORT}:${DEBUGGER_PORT}
    command: ["go", "run", "cmd/grpc/main.go"]
    environment:
      - DD_SERVICE=${APP_NAME}-grpc

  app-http-grpc:
    image: ${APP_NAME}
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - ${APP_HTTP_SERVER_PORT}:${APP_HTTP_SERVER_PORT}
      - ${APP_GRPC_SERVER_PORT}:${APP_GRPC_SERVER_PORT}
      - ${DEBUGGER_PORT}:${DEBUGGER_PORT}
    environment:
      - DD_SERVICE=${APP_NAME}-http-grpc
    command: ["go", "run", "cmd/http-grpc/main.go"]
